### ISSUE TITLE
React 18 Support?

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [okta-samples/okta-react-sample#114]
Any idea when this will be tested and verified to work with React 18?

**Comment by mraible** [comment]
Hello @ZinkNotTheMetal. I was able to upgrade to React 18 in https://github.com/okta-samples/okta-react-sample/pull/115. You can clone the branch:

```
git clone -b react-18 https://github.com/okta-samples/okta-react-sample.git
```

Or use the [Okta CLI](https://cli.okta.com):

```
okta start react --branch react-18
```

To install it, you'll need to use `npm i --force` because [semantic-ui-react doesn't support React 18 yet](https://github.com/Semantic-Org/Semantic-UI-React/issues/4354).

**Comment by mraible** [comment]
The Okta React SDK works just fine with React 18. This particular sample uses Semantic UI, which doesn't have a React 18-compatible release yet.

**Comment by aliveli186** [comment]
> The Okta React SDK works just fine with React 18. This particular sample uses Semantic UI, which doesn't have a React 18-compatible release yet.

Sorry, thought I wrote in "react-popper" repo.

**Comment by mraible** [comment]
React 18 has been merged into the `main` branch, so I'm closing this ticket. See https://github.com/okta-samples/okta-react-sample/pull/115 for more information.
